unstable_features = true
max_width = 120

group_imports = "StdExternalCrate"
imports_granularity = "Crate"

struct_lit_single_line = false
reorder_impl_items = true
use_field_init_shorthand = true

edition = "2021"
